language: java
addons:
  sonarcloud:
    organization: "srjohnjohn-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
    branches:
      - master
script:
  # other script steps might be done before running the actual analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar